// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Senai.CodeTur.Infra.Data.Contextos;

namespace Senai.CodeTur.Infra.Data.Migrations
{
    [DbContext(typeof(CodeTurContext))]
    [Migration("20200130150904_Criacao-Banco")]
    partial class CriacaoBanco
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Senai.CodeTur.Dominio.Entidades.UsuarioDominio", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnName("Email")
                    .HasColumnType("varchar(150)");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnName("Nome")
                    .HasColumnType("varchar(150)");

                b.Property<string>("Senha")
                    .IsRequired()
                    .HasColumnName("Senha")
                    .HasColumnType("varchar(15)");

                b.Property<string>("Tipo")
                    .IsRequired()
                    .HasColumnName("Tipo")
                    .HasColumnType("varchar(20)");

                b.HasKey("Id");

                b.ToTable("Usuarios");

                b.HasData(
                    new { Id = 1, Email = "admin@codetur.com", Nome = "Fernando Henrique", Senha = "Codetur@132", Tipo = "Administrador" }
                );
            });
#pragma warning restore 612, 618
        }
    }
}
